@PerfCountersApi_HostAddress = http://localhost:22788

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/
Accept: application/json

### Get Application Pools
GET {{PerfCountersApi_HostAddress}}/api/perfcounter/app-pools

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/Web%20Service/instances

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/ASP.NET%20Applications/instances

### Get category instances for a specific category

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/W3SVC_W3WP/instances

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/.NET%20CLR%20LocksAndThreads/instances

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/.NET%20CLR%20LocksAndThreads/counters?instanceName=w3wp%231__(appa)

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/.NET%20CLR%20LocksAndThreads/counters/names

##

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/TCPv4/counters

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/ASP.NET%20Apps%20v4.0.30319/counters

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/ASP.NET%20Apps%20v4.0.30319/counters?instanceName=_LM_W3SVC_1_ROOT_appa

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/ASP.NET%20Apps%20v4.0.30319/counters?instanceName=_LM_W3SVC_1_ROOT_async

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/ASP.NET%20Applications/counters/Requests%20Total?instanceName=__Total__

###

GET {{PerfCountersApi_HostAddress}}/api/perfcounter/categories/TCPv4/counters/Connections%20Established

###

POST {{PerfCountersApi_HostAddress}}/api/perfcounter/counters/values
Content-Type: application/json

[
  {
    "CategoryName": "ASP.NET Applications",
    "CounterName": "Requests Total",
    "InstanceName": "__Total__"
  },
  {
    "CategoryName": "TCPv4",
    "CounterName": "Connections Established"
  },
  {
    "CategoryName": "Processor",
    "CounterName": "% Processor Time",
    "InstanceName": "_Total"
  }
]
[{"CategoryName":"\\Process(Code)\\ID Process"},{"CategoryName":"\\Process(Code)\\Pool Paged Bytes"},{"CategoryName":"\\Process(Code)\\Handle Count"}]

###

POST {{PerfCountersApi_HostAddress}}/api/perfcounter/counters/values/over-time
Content-Type: application/json

{
  "CounterRequests": [
    {
      "CategoryName": "ASP.NET Applications",
      "CounterName": "Requests Total",
      "InstanceName": "__Total__"
    },
    {
      "CategoryName": "TCPv4",
      "CounterName": "Connections Established"
    }
  ],
  "DurationInSeconds": 5
}
